context:
  version: "2.17.1"

package:
  name: sesh
  version: ${{ version }}

source:
  url: https://github.com/joshmedeski/sesh/archive/v${{ version }}.tar.gz
  sha256: 7e36326f7308e7248695e87ba19734426edbbb6df7496bf4afa699fdcdc343e3

build:
  number: 0
  skip:
    - win
  script:
    - go build -ldflags "-s -w" -o $PREFIX/bin/
    - go-licenses save . --save_path="./license-files/"

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses
  run:
    - tmux
    - zoxide

tests:
  - script:
      - sesh --help

about:
  homepage: https://github.com/joshmedeski/sesh.git
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Smart session manager for the terminal
  description: |
    Sesh is a CLI that helps you create and manage tmux sessions quickly and easily using zoxide.

extra:
  recipe-maintainers:
    - joshmedeski
    - papanikos
